""""
Package                      Version
---------------------------- ---------
absl-py                      1.4.0
asgiref                      3.5.2
astunparse                   1.6.3
async-generator              1.10
attrs                        22.2.0
Automat                      22.10.0
cachetools                   5.3.0
certifi                      2022.6.15
cffi                         1.15.1
charset-normalizer           2.1.0
click                        8.1.3
colorama                     0.4.6
constantly                   15.1.0
cryptography                 40.0.1
cssselect                    1.2.0
cycler                       0.11.0
Django                       4.1.2
et-xmlfile                   1.1.0
exceptiongroup               1.1.1
filelock                     3.10.7
flatbuffers                  23.3.3
fonttools                    4.33.3
gast                         0.4.0
google-auth                  2.17.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.53.0
h11                          0.14.0
h5py                         3.8.0
hyperlink                    21.0.0
idna                         3.3
incremental                  22.10.0
itemadapter                  0.7.0
itemloaders                  1.0.6
jax                          0.4.7
jmespath                     1.0.1
joblib                       1.2.0
keras                        2.12.0
kiwisolver                   1.4.3
libclang                     16.0.0
lxml                         4.9.2
Markdown                     3.4.3
MarkupSafe                   2.1.2
matplotlib                   3.5.2
ml-dtypes                    0.0.4
nltk                         3.8.1
numpy                        1.22.4
oauthlib                     3.2.2
openpyxl                     3.0.10
opt-einsum                   3.3.0
outcome                      1.2.0
packaging                    21.3
pandas                       1.4.3
parsel                       1.7.0
Pillow                       9.1.1
pip                          22.0.4
Protego                      0.2.1
protobuf                     4.22.1
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycparser                    2.21
PyDispatcher                 2.0.7
PyJWT                        2.4.0
pyodbc                       4.0.35
pyOpenSSL                    23.1.1
pyparsing                    3.0.9
PySocks                      1.7.1
python-dateutil              2.8.2
pytz                         2022.1
pywin32                      306
queuelib                     1.6.2
regex                        2023.3.23
requests                     2.28.1
requests-file                1.5.1
requests-oauthlib            1.3.1
rsa                          4.9
scikit-learn                 1.2.2
scipy                        1.10.1
Scrapy                       2.8.0
seaborn                      0.12.2
service-identity             21.1.0
setuptools                   58.1.0
six                          1.16.0
sniffio                      1.3.0
sortedcontainers             2.4.0
sqlparse                     0.4.3
tensorboard                  2.12.0
tensorboard-data-server      0.7.0
tensorboard-plugin-wit       1.8.1
tensorflow                   2.12.0
tensorflow-estimator         2.12.0
tensorflow-intel             2.12.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.2.0
threadpoolctl                3.1.0
tldextract                   3.4.0
tqdm                         4.65.0
trio                         0.22.0
twilio                       7.11.0
Twisted                      22.10.0
twisted-iocpsupport          1.0.2
typing_extensions            4.5.0
tzdata                       2022.4
urllib3                      1.26.10
w3lib                        2.1.1
Werkzeug                     2.2.3
wheel                        0.40.0
wrapt                        1.14.1
wsproto                      1.2.0
zope.interface               6.0


"""



